player:
  hp: 3
  speed: 10
  shootInterval: 20
  bulletType: straight
  size: [60, 80]

enemy:
  normal:
    hp: 1
    speed: 2
    score: 10
    canShoot: false
    size: [50, 60]

  elite:
    hp: 3
    speed: 2
    score: 50
    canShoot: true
    shootInterval: 120
    bulletType: straight
    size: [60, 80]

boss:
  hp: 30
  speed: 1
  score: 500
  size: [200, 150]
  phases:
    - hpThreshold: 30
      pattern: fan
      shootInterval: 90
    - hpThreshold: 20
      pattern: fan, homing
      shootInterval: 150
    - hpThreshold: 10
      pattern: laser, homing, straight
      shootInterval: 120
