bullets:
  player:
    speed: 12
    damage: 1
    trajectory: straight
    class: PlayerBullet

  Enemy:
    speed: 8
    damage: 1
    trajectory: straight
    class: NormalEnemyBullet

  Laser:
    speed: 0
    damage: MAX_INT
    trajectory: straight
    class: LaserBullet


  Homing:
    speed: 8
    damage: 1
    thickness: 20
    class: HomingEnemyBullet

  curved:
    speed: 8
    damage: 1
    trajectory: curve
    class: CurveEnemyBullet

trajectories:
  straight:
    class: StraightTrajectory
    params: {}

  homing:
  class: HomingTrajectory
  params:
    turnStrength: 0.12


  curve:
  class: CurveTrajectory
  params:
    factor: 0.12
    gravity: 0.65
    keepSpeed: true
    minDownVy: 4.0
    maxSpeed: 18.0
