bullets:
  player:
    speed: 8
    damage: 1
    trajectory: straight

  enemy:
    speed: 4
    damage: 1

trajectories:
  straight:
    class: StraightTrajectory

  fan:
    class: FanTrajectory
    count: 5
    angleRange: 60

  spiral:
    class: SpiralTrajectory
    rotateSpeed: 0.1

  tracking:
    class: TrackingTrajectory
