interfaces:
  - Entity
  - Aircraft
  - Bullet
  - Trajectory
  - Clearable

abstract_classes:
  - AbstractEntity
  - AbstractAircraft
  - AbstractPlayerAircraft
  - AbstractEnemyAircraft
  - AbstractBullet
  - AbstractUiDialog
  - AbstractUiMenu

inheritance:
  AbstractEntity:
    implements: [Entity]

  AbstractAircraft:
    extends: AbstractEntity
    implements: [Aircraft]

  AbstractBullet:
    extends: AbstractEntity
    implements: [Bullet]

  AbstractPlayerAircraft:
    extends: AbstractAircraft

  AbstractEnemyAircraft:
    extends: AbstractAircraft

  PlayerAircraft:
    extends: AbstractPlayerAircraft

  NormalEnemy:
    extends: AbstractEnemyAircraft

  EliteEnemy:
    extends: AbstractEnemyAircraft

  BossEnemy:
    extends: AbstractEnemyAircraft

  PlayerBullet:
    extends: AbstractBullet

  NormalEnemyBullet:
    extends: AbstractBullet

  LaserBullet:
    extends: AbstractBullet
    implements: [Clearable]

  CurveEnemyBullet:
    extends: AbstractBullet

  HomingEnemyBullet:
    extends: AbstractBullet

  StraightTrajectory:
    implements: [Trajectory]

  HomingTrajectory:
    implements: [Trajectory]

  CurveTrajectory:
    implements: [Trajectory]
