game:
  title: "Thunder Fighter"
  version: "1.1.0"
  width: 800
  height: 900
  TPS: 120

difficulty:
  ENEMY_NUMBER_LIMIT: 16
  generateScore:
    GENERATE_ELITE_SCORE: 100
    GENERATE_BOSS_SCORE: 500
  stage:
    - NORMAL
    - ELITE
    - BOSS

state:
  - MENU
  - RUNNING
  - PAUSE
  - SUCCESS
  - FAIL
