props:
  shield:
    class: ShieldProp
    duration: 5000
    dropRate: 0.1

  attackUp:
    class: AttackUpProp
    duration: 8000
    attackAdd: 1
    dropRate: 0.15

  heal:
    class: HealProp
    heal: 1
    dropRate: 0.2
